Resource policies duplicity
dataquest-dev/dspace-import pull request #166
Opened 2024-10-04 20:45 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  3  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
You can see duplication in the Restricted Collection: Wikitongues Oral Histories and in all collections where the Authorization Action is READ, DEFAULT_ITEM_READ, or DEFAULT_BITSTREAM_READ.
image

## Analysis
This issue occurs because in DSpace 5, there is only a DEFAULT_READ group for the actions BITSTREAM_DEFAULT_READ and ITEM_DEFAULT_READ. In DSpace 7, these are divided into separate ITEM_DEFAULT_READ and BITSTREAM_DEFAULT_READ groups. Consequently, one group from DSpace 5 is mapped to two groups in DSpace 7.

## Solution
Since one group in DSpace 5 is split into two groups in DSpace 7, these groups are assigned the same e-persons (the only difference is in their names). Assign the READ and ITEM_DEFAULT_READ actions only to the group named COLLECTION_[uuid]ITEM_DEFAULT_READ and the BITSTREAM_DEFAULT_READ action to the group named COLLECTION[uuid]_BITSTREAM_DEFAULT_READ.

Old implementation:
![image](https://github.com/user-attachments/assets/4700ede5-0009-4a3e-b8be-786c89d9c88f)

New implementation:
![image](https://github.com/user-attachments/assets/d68e983b-eb52-486a-a219-b588dc3e63ec)
![image](https://github.com/user-attachments/assets/e5565cfa-cf61-46c8-ba8f-96f3212c027d)

2024-10-07 09:25 UTC, vidiecan requested changes

2024-10-07 09:25 UTC, vidiecan commented on src/pump/_resourcepolicy.py
> +        ITEM = "ITEM"
duplicate, use one static variable e.g., collections.ITEM otherwise you change one string and have a sync problem

2024-10-08 07:13 UTC, milanmajchrak approved these changes

2024-10-08 11:55 UTC, vidiecan requested changes

2024-10-08 11:55 UTC, vidiecan commented on src/pump/_resourcepolicy.py
> +                    if len(group_type_list) > 1:
```suggestion
                    if len(group_type_list) != 1:
```

2024-10-08 11:55 UTC, vidiecan commented on src/pump/_resourcepolicy.py
> +                    if len(group_type_list) > 1:
?

2024-10-10 12:15 UTC, merged